$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$portfolioRoot = Split-Path $PSScriptRoot -Parent
$outputDirectory = Join-Path $portfolioRoot 'public/images/portfolio/responsive'
New-Item -ItemType Directory -Force $outputDirectory | Out-Null
$sources = [ordered]@{
    'tjorven' = 'img-of-me-needs-to-be-cropped.png'
    'jenny' = 'jenny-img-needs-to-be-cropped.png'
    'jenny-detail' = 'jenny-img-back-from-side.png'
    'camera-source' = '../design/reference/train_1061.jpg'
    'camera-overview' = 'perception-overview.png'
    'camera-crop' = 'perception-crop.png'
    'camera-model' = 'perception-model.png'
    'vtol' = 'vtol-neutral.png'
    'team' = 'img-of-me-and-3-friends-having-success-and-being-happy.jpg'
}
$jpegCodec = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() | Where-Object MimeType -eq 'image/jpeg'
$manifest = [ordered]@{}
foreach ($entry in $sources.GetEnumerator()) {
    $source = [System.Drawing.Image]::FromFile((Join-Path $portfolioRoot ('docs/materials/' + $entry.Value)))
    try {
        $variants = @()
        $preview = ''
        $widths = @(48, 320, 640, 960, [Math]::Min(1440, $source.Width)) | Sort-Object -Unique
        foreach ($width in $widths) {
            if ($width -gt $source.Width) { continue }
            $height = [int][Math]::Round($source.Height * $width / $source.Width)
            $bitmap = New-Object System.Drawing.Bitmap($width, $height)
            $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
            $parameters = New-Object System.Drawing.Imaging.EncoderParameters(1)
            try {
                $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
                $graphics.DrawImage($source, 0, 0, $width, $height)
                $quality = if ($width -eq 48) { 35L } else { 78L }
                $parameters.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter([System.Drawing.Imaging.Encoder]::Quality, $quality)
                if ($width -eq 48) {
                    $stream = New-Object System.IO.MemoryStream
                    try {
                        $bitmap.Save($stream, $jpegCodec, $parameters)
                        $preview = 'data:image/jpeg;base64,' + [Convert]::ToBase64String($stream.ToArray())
                    } finally { $stream.Dispose() }
                } else {
                    $filename = $entry.Key + '-' + $width + '.jpg'
                    $bitmap.Save((Join-Path $outputDirectory $filename), $jpegCodec, $parameters)
                    $variants += '/images/portfolio/responsive/' + $filename + ' ' + $width + 'w'
                }
            } finally { $parameters.Dispose(); $graphics.Dispose(); $bitmap.Dispose() }
        }
        $manifest[$entry.Key] = @{preview = $preview; src = '/images/portfolio/responsive/' + $entry.Key + '-640.jpg'; srcset = $variants -join ', '; width = $source.Width; height = $source.Height}
    } finally { $source.Dispose() }
}
$json = $manifest | ConvertTo-Json -Depth 4
$content = '// Generated by scripts/prepare-portfolio-images.ps1. Originals remain in docs/materials.' + "`nexport const PORTFOLIO_PHOTOS = " + $json + " as const;`nexport type PortfolioPhotoName = keyof typeof PORTFOLIO_PHOTOS;`n"
[IO.File]::WriteAllText((Join-Path $portfolioRoot 'src/app/features/portfolio/portfolio-photos.ts'), $content)
Get-ChildItem $outputDirectory | Select-Object Name, Length
