"""Reproduce preprocessing with the user-corrected bottom-aligned overview."""
import argparse
import hashlib
import json
import re
from pathlib import Path
import cv2
import numpy as np

root=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser()
parser.add_argument('--perception-repo',type=Path,default=Path('D:/FastForest/GD5/perception'))
args=parser.parse_args()
config=(args.perception_repo/'config.yaml').read_text()
def number(key):
    match=re.search(r'^\s*'+re.escape(key)+r':\s*([0-9.]+)',config,re.M)
    if not match: raise ValueError('Missing configuration key: '+key)
    return float(match[1])
w,h,size=[int(number(k)) for k in ['horizontal_resolution','vertical_resolution','model_size']]
source=cv2.imread(str(root/'docs/design/reference/train_1061.jpg'))
assert source is not None and source.shape==(h,w,3), 'Camera frame dimensions must match the repository configuration'
overview_h=w//2
# User correction: discard only the top strip. The inspected repo still centres this ROI.
overview_y=h-overview_h
assert overview_y+overview_h==h
half=size//2
# Match C++ float configuration arithmetic followed by truncation to int.
crop_x=int(np.float32(np.float32(number('zoomed_image_relative_x_offset'))*np.float32(w))/np.float32(2))
crop_y=int(np.float32(overview_y)+np.float32(np.float32(number('zoomed_image_relative_y_offset'))*np.float32(overview_h))/np.float32(2))
assert size%2==0 and 0<=crop_x<=w-size and 0<=crop_y<=h-half
source_overview=source[overview_y:overview_y+overview_h,:]
overview=cv2.resize(source_overview,(size,half),interpolation=cv2.INTER_LINEAR)
crop=source[crop_y:crop_y+half,crop_x:crop_x+size].copy()
model=np.concatenate([overview,crop],axis=0)
assert model.shape==(size,size,3)
assert np.array_equal(model[half:],source[crop_y:crop_y+half,crop_x:crop_x+size])
assert np.array_equal(model[:half],cv2.resize(source_overview,(size,half)))
for name,img in [('overview',overview),('crop',crop),('model',model)]:
    assert cv2.imwrite(str(root/f'docs/materials/perception-{name}.png'),img)
metadata=dict(overviewAlignment="bottom (user correction; local repo uses centre)",source=dict(width=w,height=h),overview=dict(x=0,y=overview_y,width=w,height=overview_h),crop=dict(x=crop_x,y=crop_y,width=size,height=half),model=dict(width=size,height=size,split=half),provenance={str(p):hashlib.sha256((args.perception_repo/p).read_bytes()).hexdigest() for p in ['config.yaml','src/detection/processing/ModelImageLayout.cpp','src/detection/processing/ImageProcessor.cpp']})
(root/'src/app/features/portfolio/perception-layout.ts').write_text('// Generated by scripts/prepare-perception-images.py; repository geometry with user-corrected bottom-aligned overview.\nexport const PERCEPTION_LAYOUT = '+json.dumps(metadata,indent=2)+' as const;\n',encoding='utf-8')
print(json.dumps(metadata,indent=2))
