name: Deploy Portfolio # TODO: change

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.FRITZ_BOX_IP }}
          username: ${{ secrets.RASPI_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /docker/portfolio || exit 1
            git pull || exit 2
            docker-compose down || exit 3
            docker-compose up -d --build || exit 4
          # script to execute within the raspi  # TODO: change

# TODO: add secrets to repo

