// Generated by scripts/prepare-perception-images.py; repository geometry with user-corrected bottom-aligned overview.
export const PERCEPTION_LAYOUT = {
  "overviewAlignment": "bottom (user correction; local repo uses centre)",
  "source": {
    "width": 1920,
    "height": 1080
  },
  "overview": {
    "x": 0,
    "y": 120,
    "width": 1920,
    "height": 960
  },
  "crop": {
    "x": 480,
    "y": 432,
    "width": 960,
    "height": 480
  },
  "model": {
    "width": 960,
    "height": 960,
    "split": 480
  },
  "provenance": {
    "config.yaml": "5227fb46e2833860341688cdc74e49bca50c53abe5bec5ecee73837e2f1c410e",
    "src/detection/processing/ModelImageLayout.cpp": "5775467e49b56e037b1c9143dc0054b249770b22c1c2373632133d1fc7ef4a78",
    "src/detection/processing/ImageProcessor.cpp": "77af580d758760b049afa813162d210c79f2b018bdc4039f989a7ca712f16f3f"
  }
} as const;
